
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false # For local development. Set to false if you want to use the hostname in a DNS-enabled environment
    hostname: ${HOSTNAME:localhost}
    non-secure-port-enabled: true
    secure-port-enabled: false
    non-secure-port: ${server.port}
    secure-port: 443

spring:
  application:
    name: inventories
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/inventory-product-db} #Actualizar con el valor de tu despliegue local de MySQL.
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${DB_USER:root} #Actualizar con el valor de tu usuario.
    password: ${DB_PASSWORD:mysql} #Actualizar con el valor de tu contraseña de root.
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: ${PORT:8081}

springdoc:
  api-docs:
    path: /swagger-doc/v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-doc/swagger-ui.html

info:
  project:
    version: "@project.version@"
    title: "@project.name@"
    description: "@project.description@"